name: Global Formatter
run-name: Format - ${{ github.ref }}, ${{ github.event_name }}
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: chartboost/ruff-action@v1
        with:
          version: "v0.4.2"
          args: format --check
